# Generated by slsa-autotools scan.yml
# https://github.com/lee-mcfaul2/slsa-autotools @ 3ff1907cb0fd9f8570c50b2b2886800f747d442e
#
# Every apt package below is pinned to both an exact version
# and the SHA256 of its .deb as served by
# snapshot.ubuntu.com at 20260422T180000Z. Any drift in the
# served bytes will fail the sha256sum check at image build.
#
# This file is regenerated by scan.yml whenever it is run.
# Hand edits are preserved through the next run only if you
# re-run scan.yml yourself; otherwise a fresh run will
# overwrite. Editing individual SHA256 values is safe — the
# verification step is purely local to this file.

FROM ubuntu@sha256:c4a8d5503dfb2a3eb8ab5f807da5bc69a85730fb49b5cfca2330194ebcc41c7b

ENV DEBIAN_FRONTEND=noninteractive

# Step 1: bootstrap ca-certificates from the default HTTP
# archive so we can reach snapshot.ubuntu.com over HTTPS.
RUN apt-get update -qq \
 && apt-get install -y --no-install-recommends ca-certificates

# Step 2: redirect apt to the pinned snapshot. All later
# apt traffic is immutable indefinitely.
RUN set -eu \
 && printf '%s\n' \
    'deb https://snapshot.ubuntu.com/ubuntu/20260422T180000Z/ noble main restricted universe multiverse' \
    'deb https://snapshot.ubuntu.com/ubuntu/20260422T180000Z/ noble-updates main restricted universe multiverse' \
    'deb https://snapshot.ubuntu.com/ubuntu/20260422T180000Z/ noble-security main restricted universe multiverse' \
    > /etc/apt/sources.list \
 && rm -f /etc/apt/sources.list.d/*.sources /etc/apt/sources.list.d/*.list \
 && apt-get update -qq

# Step 3: download each pinned .deb, verify its SHA256,
# then install. A single RUN so failure aborts the layer
# atomically. Packages are deduplicated and sorted.
RUN set -eux \
 && mkdir -p /tmp/debs && cd /tmp/debs \
 && apt-get download \
      autoconf=2.71-3 \
      automake=1:1.16.5-1.3ubuntu1 \
      autopoint=0.21-14ubuntu2 \
      bash=5.2.21-2ubuntu4 \
      binutils=2.42-4ubuntu2.10 \
      bsdextrautils=2.39.3-9ubuntu6.5 \
      coreutils=9.4-3ubuntu6.2 \
      cpp-13-x86-64-linux-gnu=13.3.0-6ubuntu2~24.04.1 \
      dash=0.5.12-6ubuntu5 \
      diffutils=1:3.10-1build1 \
      file=1:5.45-3build1 \
      findutils=4.9.0-5build1 \
      gcc=4:13.2.0-7ubuntu1 \
      gcc-13-x86-64-linux-gnu=13.3.0-6ubuntu2~24.04.1 \
      gettext=0.21-14ubuntu2 \
      git=1:2.43.0-1ubuntu7.3 \
      grep=3.11-4build1 \
      groff-base=1.23.0-3build2 \
      gzip=1.12-1ubuntu3.1 \
      hostname=3.23+nmu2ubuntu2 \
      libc-bin=2.39-0ubuntu8.7 \
      libc6=2.39-0ubuntu8.7 \
      libc6-dev=2.39-0ubuntu8.7 \
      libcurl4-openssl-dev=8.5.0-2ubuntu10.8 \
      libgcc-13-dev=13.3.0-6ubuntu2~24.04.1 \
      libgmp10=2:6.3.0+dfsg-2ubuntu6.1 \
      libmagic-mgc=1:5.45-3build1 \
      libmagic1t64=1:5.45-3build1 \
      libtool=2.4.7-7build1 \
      libxml2-dev=2.9.14+dfsg-1.3ubuntu3.7 \
      linux-libc-dev=6.8.0-110.110 \
      m4=1.4.19-4build1 \
      make=4.3-4.1build2 \
      mawk=1.3.4.20240123-1build1 \
      perl-base=5.38.2-3.2ubuntu0.2 \
      pkgconf=1.8.1-2build1 \
      po4a=0.69-1 \
      sed=4.9-2build1 \
      tar=1.35+dfsg-3build1 \
      xz-utils=5.6.1+really5.4.5-1ubuntu0.2 \
      zlib1g-dev=1:1.3.dfsg-3.1ubuntu2.1 \
 && printf '%s\n' \
      '013ec4c2fa3373840f20b202a55b62b66ae450b9e969d5e943001a43a1aec5cc  bsdextrautils_2.39.3-9ubuntu6.5_amd64.deb' \
      '015b65ef176021c1846ec8b6152167d5d266c1949ec30ee3367e95fa2b2ead27  tar_1.35+dfsg-3build1_amd64.deb' \
      '023cbe9dbf0af87f10e54e342c67571874e412b9950d89c6cd7b010be2e67c3c  zlib1g-dev_1.3.dfsg-3.1ubuntu2.1_amd64.deb' \
      '02f2ca4183ea0578c6bbc0849669f0ea8749d254ed48738055a8695fb10ec93a  libxml2-dev_2.9.14+dfsg-1.3ubuntu3.7_amd64.deb' \
      '099bb129f543adc4c14203334b0fa0a909f8bf038c4d56bc9cc7c774ebf78f87  git_2.43.0-1ubuntu7.3_amd64.deb' \
      '0e0bb8b25153ed1c44ab92bc219eed469fcb5820c5c0bc6454b2fd366a33d3ee  gcc_13.2.0-7ubuntu1_amd64.deb' \
      '17dae1d6e803d0304e318f451c8abf62cbd5bb2a0068300cdeea77c62075b895  file_5.45-3build1_amd64.deb' \
      '1cd698c64bb1100a505a71894321716d807dc976c26d488b339f0b6289aad2fc  groff-base_1.23.0-3build2_amd64.deb' \
      '1fe6a815b56c7b6e9ce4086a363f09444bbd0a0d30e230c453d0b78e44b57a99  make_4.3-4.1build2_amd64.deb' \
      '285f8a505dfa8e1b33f357a9d8d3477ad35bf18c0b34771a6df4c25923f3ae0d  libgmp10_6.3.0+dfsg-2ubuntu6.1_amd64.deb' \
      '2ca48bf0c2d6465bc39322899715a85d934b4d7442dd5586a7bebbe3ce0f806b  cpp-13-x86-64-linux-gnu_13.3.0-6ubuntu2~24.04.1_amd64.deb' \
      '30ea715845a1863abd55d11e47ab91513130bf347852d4cdeae69e9d98fa795c  m4_1.4.19-4build1_amd64.deb' \
      '38e3e603aeca8cbbaefce34eec6b8190f53939425bf2eb2c8a3956d0a947a630  libc-bin_2.39-0ubuntu8.7_amd64.deb' \
      '3a818142e591e7212c5c7e58af40fb6f8658fbf47531057d2d0265400d8300a1  libcurl4-openssl-dev_8.5.0-2ubuntu10.8_amd64.deb' \
      '42853d892435cf2ed08dfda92ba77b13bca85f31689256096415921d00cd59c8  autopoint_0.21-14ubuntu2_all.deb' \
      '526790098bf711ca4fa21cfdf334acdb9cd8e59d3b5732174ceca8ebc8eba98b  perl-base_5.38.2-3.2ubuntu0.2_amd64.deb' \
      '5338a17b0c7da20280097d5730ab640c8fcc2b4547acdda29361b27675b937c6  gettext_0.21-14ubuntu2_amd64.deb' \
      '5ae9a98e73545002cd891f028859941af2a3c760cb6190e635c7ef36953912de  automake_1.16.5-1.3ubuntu1_all.deb' \
      '73de311a21e094e29ac01527d2b52226cc87fde0a5b57032902251b426d92c66  bash_5.2.21-2ubuntu4_amd64.deb' \
      '834a58031069d97d7cfb8b2f5bfd5effc69cecf7f30cc362071875f1f8dc1828  pkgconf_1.8.1-2build1_amd64.deb' \
      '925187570891a3b0af6a1423bdc91492a33c231fa39974ed91efb3ae4ce530fc  xz-utils_5.6.1+really5.4.5-1ubuntu0.2_amd64.deb' \
      '955644e8bc2930a9bf8eea5e4c2237c8a118c1e2ac2845b993b6f7f35eefd293  libc6_2.39-0ubuntu8.7_amd64.deb' \
      '96490acdee09245bb47ff4684dc59a7ac3b29619da868ef3e9d8323c61a02ac4  findutils_4.9.0-5build1_amd64.deb' \
      '9d1d707179675d38e024bb13613b1d99e0d33fa6c45e5f3bcba19340781781d3  libtool_2.4.7-7build1_all.deb' \
      'a09b856849cf36190f8cd39da33486b14bcaf81b592530b2f3236da17daaad2f  sed_4.9-2build1_amd64.deb' \
      'a134b0319a82d14581b3a14820d2832af4ec9778ed8b9b4ddaeecfb0555ec325  gcc-13-x86-64-linux-gnu_13.3.0-6ubuntu2~24.04.1_amd64.deb' \
      'a9f6ba49005d117cdd40b80985a2c078671bb7922b32376432e1a096e23a4f10  po4a_0.69-1_all.deb' \
      'b10814b7ada5e8ae3182707bb17a492b17ab453efeb145c7b34fe5250cf0edb3  linux-libc-dev_6.8.0-110.110_amd64.deb' \
      'b3b5a84181a38fd191820b2cdcc1a3eeb1cd6333ad472f2092f96e81047e9c74  binutils_2.42-4ubuntu2.10_amd64.deb' \
      'bbf5a155039042634961a61276650631ee47b9e721f91f8dbb731b0bbe046df3  libc6-dev_2.39-0ubuntu8.7_amd64.deb' \
      'c9b3109d868c1e5a26f0bd10e005171420d83f6da84a527aa6293bc350892504  hostname_3.23+nmu2ubuntu2_amd64.deb' \
      'cc3f9f7a1e576173fb59c36652c0a67c6426feae752b352404ba92dfcb1b26c9  autoconf_2.71-3_all.deb' \
      'cd689db2691edaa10f37329307292796bb599e722e0505c79e14caaa1fe9a93a  libgcc-13-dev_13.3.0-6ubuntu2~24.04.1_amd64.deb' \
      'd3ea567e3c25ebcd272e541ad49c447bc1d7f3720b8081132177ddb3ca9b1f96  gzip_1.12-1ubuntu3.1_amd64.deb' \
      'd623abbb182acfead9d6352252e687674b6e5b3b79d42aa1324b08a3a6e1131b  coreutils_9.4-3ubuntu6.2_amd64.deb' \
      'dc7f7f4dad4b48f6012ea65de3198d8376604afef39f06d65ec6167740e203c9  mawk_1.3.4.20240123-1build1_amd64.deb' \
      'e97728d8deaa51300255f0572bbd68b9549e0894a184c056dc420fc4e0ba0781  dash_0.5.12-6ubuntu5_amd64.deb' \
      'f0ed0e314a63ae1b7e5403d7e43a26c6e0c0ee69e9a305babcf9c6775607377a  libmagic-mgc_5.45-3build1_amd64.deb' \
      'f9b8ff6528114ba4c6a9ec94570c838a266f9f196969ae08f310725fa830d958  diffutils_3.10-1build1_amd64.deb' \
      'fc0fdc5983ea3d3579ccf335e51dec69684a0dd9bb915734999c5733add9507a  grep_3.11-4build1_amd64.deb' \
      'fc2319f342c437e044ccf854e0c95bd472a7eb0b9363e1f76ad1524ab04df68e  libmagic1t64_5.45-3build1_amd64.deb' \
    > SHA256SUMS \
 && sha256sum -c SHA256SUMS \
 && dpkg -i *.deb \
 && cd / && rm -rf /tmp/debs \
 && apt-get clean \
 && rm -rf /var/lib/apt/lists/*

# Re-register the workspace as a safe git directory for
# the container user. Needed for any later git operation
# this image's consumers may want to do.
RUN git config --global --add safe.directory '*'
